services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ql-dat-phong-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD:-YourStrong(!)Password}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
